(() => {
  'use strict';
  const STORAGE_KEY = 'bloom.tasks.v1';
  const LISTS_KEY = 'bloom.lists.v1';
  const seedLists = ['Personal', 'Work', 'Ideas', 'Wellbeing'];
  const seedTasks = [
    { id: 'seed-1', title: 'Plan the week ahead', note: 'Leave a little room for the unexpected.', list: 'Personal', date: todayISO(), time: '09:30', priority: 'medium', done: false, createdAt: 1 },
    { id: 'seed-2', title: 'Send the project update', note: 'Share the latest designs with the team.', list: 'Work', date: todayISO(), time: '11:00', priority: 'high', done: false, createdAt: 2 },
    { id: 'seed-3', title: 'Pick up something nice for dinner', note: '', list: 'Personal', date: todayISO(), time: '', priority: 'low', done: true, createdAt: 3 },
    { id: 'seed-4', title: 'Make time for a proper lunch', note: 'Step away from the screen for a bit.', list: 'Wellbeing', date: todayISO(), time: '13:00', priority: 'low', done: false, createdAt: 4 },
    { id: 'seed-5', title: 'Sketch out the new landing page', note: 'Just get the first few ideas down.', list: 'Ideas', date: tomorrowISO(), time: '', priority: 'medium', done: false, createdAt: 5 }
  ];
  const read = (key, fallback) => { try { const value = JSON.parse(localStorage.getItem(key)); return Array.isArray(value) ? value : fallback; } catch { return fallback; } };
  let tasks = read(STORAGE_KEY, seedTasks);
  let lists = read(LISTS_KEY, seedLists);
  let activeView = 'all', activeList = '', activeFilter = 'all', query = '', toastTimer;
  const $ = (selector) => document.querySelector(selector);
  const taskList = $('#taskList'), modal = $('#modalBackdrop'), form = $('#taskForm');
  function todayISO(){const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,10)}
  function tomorrowISO(){const date=new Date();date.setDate(date.getDate()+1);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,10)}
  function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks));localStorage.setItem(LISTS_KEY,JSON.stringify(lists))}
  function escapeHTML(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function formatDate(value){if(!value)return 'No due date';if(value===todayISO())return 'Today';if(value===tomorrowISO())return 'Tomorrow';return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(`${value}T12:00:00`))}
  function formatTime(value){if(!value)return '';const [hour,minute]=value.split(':').map(Number);return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,hour,minute))}
  function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2300)}
  function renderLists(){const host=$('#listNav');host.innerHTML=lists.map(name=>`<a href="#" class="list-link ${activeList===name?'selected':''}" data-list="${escapeHTML(name)}"><span class="list-dot"></span>${escapeHTML(name)}<small>${tasks.filter(task=>task.list===name&&!task.done).length}</small></a>`).join('');const select=$('#taskListSelect');const previous=select.value;select.innerHTML=lists.map(name=>`<option value="${escapeHTML(name)}">${escapeHTML(name)}</option>`).join('');if(lists.includes(previous))select.value=previous;$('#navTotal').textContent=tasks.filter(task=>!task.done).length}
  function visibleTasks(){let result=tasks.slice();if(activeList)result=result.filter(task=>task.list===activeList);if(activeView==='today')result=result.filter(task=>task.date===todayISO()&&!task.done);if(activeView==='upcoming')result=result.filter(task=>task.date>todayISO()&&!task.done);if(activeView==='completed')result=result.filter(task=>task.done);if(activeFilter==='active')result=result.filter(task=>!task.done);if(activeFilter==='completed')result=result.filter(task=>task.done);if(query)result=result.filter(task=>`${task.title} ${task.note} ${task.list}`.toLowerCase().includes(query));const sort=$('#sortSelect').value;if(sort==='priority'){const rank={high:0,medium:1,low:2};result.sort((a,b)=>rank[a.priority]-rank[b.priority])}else if(sort==='title')result.sort((a,b)=>a.title.localeCompare(b.title));else result.sort((a,b)=>(a.done-b.done)||(a.date||'9999').localeCompare(b.date||'9999')||(a.time||'99:99').localeCompare(b.time||'99:99')||a.createdAt-b.createdAt);return result}
  function renderTasks(){renderLists();const visible=visibleTasks();if(!visible.length){const emptyTitle=query?'No matching tasks':activeView==='completed'?'Your wins will show up here':'A little space to start something';const emptySub=query?'Try a different search.':'Add a task when you are ready to get going.';taskList.innerHTML=`<div class="empty-state"><div class="empty-illustration">✿</div><div class="empty-title">${emptyTitle}</div><div class="empty-sub">${emptySub}</div></div>`}else{taskList.innerHTML=visible.map((task,index)=>`<article class="task-row ${task.done?'is-done':''}" style="animation-delay:${Math.min(index*35,210)}ms"><input class="task-check" type="checkbox" aria-label="Mark ${escapeHTML(task.title)} ${task.done?'to do':'done'}" data-toggle="${escapeHTML(task.id)}" ${task.done?'checked':''}><div class="task-copy"><div class="task-title">${escapeHTML(task.title)}</div>${task.note?`<div class="task-note">${escapeHTML(task.note)}</div>`:''}</div><div class="task-meta"><span class="task-list-label">${escapeHTML(task.list)}</span><span class="task-date">${formatDate(task.date)}${task.time?` · ${formatTime(task.time)}`:''}</span><span class="priority priority-${escapeHTML(task.priority)}">${escapeHTML(task.priority[0].toUpperCase()+task.priority.slice(1))}</span></div><button class="task-action" aria-label="Edit task" data-edit="${escapeHTML(task.id)}">···</button></article>`).join('')}
    const todayDone=tasks.filter(task=>task.done&&task.date===todayISO()).length;const open=tasks.filter(task=>!task.done);const total=tasks.length;$('#inProgressCount').textContent=open.length;$('#completedCount').textContent=todayDone;$('#progressBar').style.width=`${total?Math.round(tasks.filter(task=>task.done).length/total*100):0}%`;$('#allCount').textContent=tasks.length;$('#todoCount').textContent=tasks.filter(task=>!task.done).length;$('#doneCount').textContent=tasks.filter(task=>task.done).length;$('#listFooter').textContent=`${visible.length} ${visible.length===1?'task':'tasks'} · ${tasks.filter(task=>task.done).length} little ${tasks.filter(task=>task.done).length===1?'win':'wins'} so far`;const next=open.filter(task=>task.date>=todayISO()&&task.time).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];$('#nextTime').textContent=next?formatTime(next.time):'—';$('#nextTaskLabel').textContent=next?next.title:'nothing on the clock';$('#sectionTitle').innerHTML=`${activeList?escapeHTML(activeList):activeView==='today'?'Today':activeView==='upcoming'?'Coming up':activeView==='completed'?'Your little wins':'The to-do list'}<span class="title-spark">✳</span>`;$('#breadcrumb').textContent=activeList||({all:'My tasks',today:'Today',upcoming:'Upcoming',completed:'Completed'}[activeView]);$('.main-nav .active')?.classList.remove('active');document.querySelector(`.nav-item[data-view="${activeView}"]`)?.classList.add('active')}
  function openModal(task=null){form.reset();$('.form-control')&&document.querySelectorAll('.form-control').forEach(control=>control.classList.remove('invalid'));$('#titleError').textContent='';$('#editTaskId').value=task?.id||'';$('#modalTitle').innerHTML=`${task?'A little edit':'Add a task'}<span class="title-spark">✳</span>`;$('#saveTask').innerHTML=`<span>✳</span> ${task?'Save changes':'Add task'}`;$('#taskTitle').value=task?.title||'';$('#taskNotes').value=task?.note||'';$('#taskListSelect').value=task?.list||activeList||lists[0];$('#taskDate').value=task?.date||todayISO();$('#taskTime').value=task?.time||'';$('#taskPriority').value=task?.priority||'medium';modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>$('#taskTitle').focus(),100)}
  function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
  function validateTitle(){const input=$('#taskTitle'),value=input.value.trim();if(!value){input.classList.add('invalid');$('#titleError').textContent='Give this task a name to get started.';return false}if(value.length<2){input.classList.add('invalid');$('#titleError').textContent='Use at least two characters.';return false}input.classList.remove('invalid');$('#titleError').textContent='';return true}
  function setView(view){activeView=view;activeList='';activeFilter='all';document.querySelectorAll('.filter-tab').forEach(tab=>tab.classList.toggle('selected',tab.dataset.filter==='all'));renderTasks()}
  $('#headerDate').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date());
  $('#greeting').innerHTML=`Make today<br />a <span>${new Date().getHours()<12?'good one.':new Date().getHours()<18?'bright one.':'gentle one.'}</span> <span class="wave">✳</span>`;
  $('#openModal').addEventListener('click',()=>openModal());$('#closeModal').addEventListener('click',closeModal);$('#cancelModal').addEventListener('click',closeModal);modal.addEventListener('click',event=>{if(event.target===modal)closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});$('#taskTitle').addEventListener('input',()=>{$('#taskTitle').classList.remove('invalid');$('#titleError').textContent=''});
  form.addEventListener('submit',event=>{event.preventDefault();if(!validateTitle())return;const id=$('#editTaskId').value;const existing=tasks.find(task=>task.id===id);const task={id:id||`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,title:$('#taskTitle').value.trim(),note:$('#taskNotes').value.trim(),list:$('#taskListSelect').value,date:$('#taskDate').value,time:$('#taskTime').value,priority:$('#taskPriority').value,done:existing?.done||false,createdAt:existing?.createdAt||Date.now()};if(existing)tasks=tasks.map(item=>item.id===id?task:item);else tasks.push(task);persist();renderTasks();closeModal();showToast(existing?'Your task has been updated.':'A new little step, added.')});
  taskList.addEventListener('change',event=>{const id=event.target.dataset.toggle;if(!id)return;const task=tasks.find(item=>item.id===id);if(!task)return;task.done=event.target.checked;persist();renderTasks();showToast(task.done?'One little win. Nicely done!':'Back on your list.')});taskList.addEventListener('click',event=>{const id=event.target.closest('[data-edit]')?.dataset.edit;if(!id)return;const task=tasks.find(item=>item.id===id);if(task)openModal(task)});
  document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>setView(item.dataset.view)));document.querySelectorAll('.filter-tab').forEach(item=>item.addEventListener('click',()=>{activeFilter=item.dataset.filter;document.querySelectorAll('.filter-tab').forEach(tab=>tab.classList.toggle('selected',tab===item));renderTasks()}));$('#listNav').addEventListener('click',event=>{const link=event.target.closest('[data-list]');if(!link)return;event.preventDefault();activeList=link.dataset.list;activeView='all';activeFilter='all';document.querySelectorAll('.filter-tab').forEach(tab=>tab.classList.toggle('selected',tab.dataset.filter==='all'));renderTasks()});$('#searchInput').addEventListener('input',event=>{query=event.target.value.trim().toLowerCase();renderTasks()});$('#sortSelect').addEventListener('change',renderTasks);$('#addList').addEventListener('click',()=>{const name=prompt('What would you like to call your new list?');if(name===null)return;const cleaned=name.trim();if(cleaned.length<2){showToast('List names need at least two characters.');return}if(lists.some(list=>list.toLowerCase()===cleaned.toLowerCase())){showToast('You already have a list with that name.');return}lists.push(cleaned);activeList=cleaned;activeView='all';persist();renderTasks();showToast(`Your ${cleaned} list is ready.`)});$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');$('#themeToggle').textContent=dark?'☀':'☾';localStorage.setItem('bloom.dark',dark?'1':'0')});if(localStorage.getItem('bloom.dark')==='1'){document.body.classList.add('dark');$('#themeToggle').textContent='☀'}
  renderTasks();
})();
